import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/providers/providers";
import clsx from "clsx";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			suppressHydrationWarning
			lang="en"
		>
			<body className={clsx("min-h-screen")}>
				<Providers themeProps={{ defaultTheme: "light" }}>{children}</Providers>
			</body>
		</html>
	);
}
